main/Models/ErrorViewModel.cs
namespace myfinance_web_dotnet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

main/Models/PlanoContaModel.cs
namespace myfinance_web_dotnet.Models
{
    public class PlanoContaModel
    {
        public int? ID {get; set;}
        public string Descricao {get; set;}
        public string Tipo {get; set;}
    }
}

main/Models/TransacaoModel.cs
using domain.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace myfinance_web_dotnet.Models
{
    public class TransacaoModel
    {
        public int? ID {get; set;}
        public string Historico {get; set;}
        public DateTime Data {get; set;}
        public decimal Valor {get; set;}
        public int PlanoContaID {get; set;}
        public string? Tipo{get; set;}
        public IEnumerable<SelectListItem>? ListaPlanoContas {get; set;}
    }
}

main/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Models;

namespace myfinance_web_dotnet.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

main/Controllers/PlanoContaController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Models;
using service.Interfaces;
using domain.Entities;


namespace myfinance_web_dotnet.Controllers
{
    public class PlanoContaController : Controller
    {
        private readonly ILogger<PlanoContaController> _logger;
        private readonly IPlanoContaService _planoContaService;
        public PlanoContaController(
            ILogger<PlanoContaController> logger,
            IPlanoContaService planoContaService
        )
        {
            _logger = logger;
            _planoContaService = planoContaService;

        }
        public IActionResult Index()
        {
            var listaPlanoContas = _planoContaService.ListarRegistros();
            List<PlanoContaModel> listaPlanoContaModel = new List<PlanoContaModel>();
            foreach (var item in listaPlanoContas)
            {
                var itemPlanoConta = new PlanoContaModel()
                {
                    ID = item.ID,
                    Descricao = item.Descricao,
                    Tipo = item.Tipo
                };
                listaPlanoContaModel.Add(itemPlanoConta);
            }
            ViewBag.ListaPlanoConta = listaPlanoContaModel;
            return View();
        }
        public IActionResult Cadastrar(int? ID)
        {
            if (ID != null)
            {
                var planoConta = _planoContaService.RetornarRegistro((int)ID);
                var planoContaModel = new PlanoContaModel()
                {
                    ID = planoConta.ID,
                    Descricao = planoConta.Descricao,
                    Tipo = planoConta.Tipo
                };
                return View(planoContaModel);   
            }
            return View();
            
        }
        [HttpPost]
        [Route("Cadastrar")]
        public IActionResult Cadastrar(PlanoContaModel model)
        {
            var planoConta = new PlanoConta()
            {
                ID = model.ID,
                Descricao = model.Descricao,
                Tipo = model.Tipo,
            };
            _planoContaService.Cadastrar(planoConta);
            return RedirectToAction("Index");
        }
        public IActionResult Excluir(int ID)
        {
            _planoContaService.Excluir(ID);
            return RedirectToAction("Index");
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

main/Controllers/TransacaoController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using myfinance_web_dotnet.Models;
using service.Interfaces;
using domain.Entities;


namespace myfinance_web_dotnet.Controllers
{
    public class TransacaoController : Controller
    {
        private readonly ILogger<TransacaoController> _logger;
        private readonly ITransacaoService _transacaoService;
        private readonly IPlanoContaService _planoContaService;
        public TransacaoController(
            ILogger<TransacaoController> logger,
            ITransacaoService transacaoService,
            IPlanoContaService planoContaService
        )
        {
            _logger = logger;
            _transacaoService = transacaoService;
            _planoContaService = planoContaService;

        }
        public IActionResult Index()
        {
            var listaTransacao = _transacaoService.ListarRegistros();
            List<TransacaoModel> listaTransacaoModel = new List<TransacaoModel>();
            foreach (var item in listaTransacao)
            {
                var itemTransacao = new TransacaoModel()
                {
                    ID = item.ID,
                    Historico = item.Historico,
                    Data = item.Data,
                    Valor = item.Valor,
                    Tipo = item.PlanoConta.Tipo,
                    PlanoContaID = item.PlanoContaID,
                };
                listaTransacaoModel.Add(itemTransacao);
            }
            ViewBag.ListaTransacao = listaTransacaoModel;
            return View();
        }
        public IActionResult Cadastrar(int? ID)
        {
            var listaPlanoContas = new SelectList(_planoContaService.ListarRegistros(), "ID", "Descricao");

            var transacaoModel = new TransacaoModel(){
                Data = DateTime.Now,
                ListaPlanoContas = listaPlanoContas
            };
            if (ID != null)
            {
                var transacao = _transacaoService.RetornarRegistro((int)ID);
                transacaoModel.ID = transacao.ID;
                transacaoModel.Historico = transacao.Historico;
                transacaoModel.Data = transacao.Data;
                transacaoModel.Valor = transacao.Valor;
                transacaoModel.Tipo = transacao.PlanoConta.Tipo;
                transacaoModel.PlanoContaID = transacao.PlanoContaID;
            }

            return View(transacaoModel);
            
        }
        [HttpPost]
        public IActionResult Cadastrar(TransacaoModel model)
        {
            var transacao = new Transacao()
            {
                ID = model.ID,
                Historico = model.Historico,
                Data = model.Data,
                Valor = model.Valor,
                PlanoContaID = model.PlanoContaID,
            };
            _transacaoService.Cadastrar(transacao);
            return RedirectToAction("Index");
        }
        public IActionResult Excluir(int ID)
        {
            _transacaoService.Excluir(ID);
            return RedirectToAction("Index");
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

main/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

main/Views/PlanoConta/Index.cshtml
@{
    ViewData["Title"] = "Plano de Contas";
}
<h1>
    @ViewData["Title"]
</h1>
<button type="button" class="btn btn-block btn-primary" onclick="Novo()">Criar item Plano de Conta</button>
<br />
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Descrição</th>
        <th>Tipo</th>
        <th>#</th>
        <th>#</th>
    </tr>

    @{
        foreach (var item in (List<PlanoContaModel>)ViewBag.ListaPLanoConta)
            {
                <tr>
                    <td>@item.ID</td>
                    <td>@item.Descricao</td>
                    <td>@item.Tipo</td>
                    <td><button type="button" class="btn btn-block btn-outline-warning" onclick="Atualizar(@item.ID.ToString())">Editar</button></td>
                    <td><button type="button" class="btn btn-block btn-outline-danger" onclick="Excluir(@item.ID.ToString())">Excluir</button></td>
                </tr>
            }
    }
</table>

<script>
    function Novo() {
        window.location.href = '/PlanoConta/Cadastrar/';
    }

    function Atualizar(id) {
        window.location.href = '/PlanoConta/Cadastrar/' + id;
    }

    function Excluir(id) {
        if (confirm('Deseja realmente excluir este item?')) {
            window.location.href = '/PlanoConta/Excluir/' + id;
        }
    }
</script>

main/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myfinance_web_dotnet</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myfinance_web_dotnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">myfinance_web_dotnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlanoConta" asp-action="Index">Plano de Contas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacao" asp-action="Index">Transações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - myfinance_web_dotnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

main/Views/Transacao/Cadastrar.cshtml
@model myfinance_web_dotnet.Models.TransacaoModel
@{
    ViewData["Title"] = "Registrar Transação Financeira";
}

<h1>@ViewData["Title"]</h1>

<div>
    <form asp-controller="Transacao" asp-action="Cadastrar" method="post">
        <input type="hidden" asp-for="ID"/><br />
        <div class="form-group">
            <label>Data:</label><br />
            <input type="date" class="form-control" asp-for="Data" />
        </div>

        <div class="form-group">
            <label>Valor:</label><br />
            <input type="text" class="form-control" asp-for="Valor" step="0.01"/>
        </div>

        <div class="form-group">
            <label>Plano de Conta:</label><br />
            @Html.DropDownListFor(model => model.PlanoContaID, Model.ListaPlanoContas, "Selecione um plano de conta", new { @class = "form-control" })   
        </div>

        <div class="form-group">
            <label>Histórico:</label><br />
            <input type="text" class="form-control" asp-for="Historico" /><br />
        </div>
        <br />
        <br />
        <button type="submit" class="btn btn-block btn-success">Registrar</button>
    </form>
</div>

main/Views/Transacao/Index.cshtml
@{
    ViewData["Title"] = "Transações Financeiras";
}
<h1>
    @ViewData["Title"]
</h1>
<button type="button" class="btn btn-block btn-primary" onclick="Novo()">Registrar transação</button>
<br />
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Histórico</th>
        <th>Tipo</th>
        <th>Valor</th>
        <th>Data</th>
        <th>#</th>
        <th>#</th>
    </tr>

    @{
        foreach (var item in (List<TransacaoModel>)ViewBag.ListaTransacao)
            {
                <tr>
                    <td>@item.ID</td>
                    <td>@item.Historico</td>
                    <td>@item.Tipo</td>
                    <td>@item.Valor</td>
                    <td>@item.Data</td>
                    <td><button type="button" class="btn btn-block btn-outline-warning" onclick="Atualizar(@item.ID.ToString())">Editar</button></td>
                    <td><button type="button" class="btn btn-block btn-outline-danger" onclick="Excluir(@item.ID.ToString())">Excluir</button></td>
                </tr>
            }
    }
</table>

<script>
    function Novo() {
        window.location.href = '/Transacao/Cadastrar/';
    }

    function Atualizar(id) {
        window.location.href = '/Transacao/Cadastrar/' + id;
    }

    function Excluir(id) {
        if (confirm('Deseja realmente excluir este item?')) {
            window.location.href = '/Transacao/Excluir/' + id;
        }
    }
</script>